//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casino.AdminPortal.EntityDataModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int PlayerId { get; set; }
        public string Name { get; set; }
        public string ContactNumber { get; set; }
        public string EmailId { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public decimal AccountBalance { get; set; }
        public byte[] IdentityProof { get; set; }
        public int BlockedAmount { get; set; }
    }
}
